### ISSUE TITLE
BUG: controller > aggregate > parse(req.body) 

### ISSUE THREAD

**Issue by nadeemramsing** [adarshasnah/mongoose-rest-query#1]
BUG: number getting transformed into ObjectId.

What I did (from Angular App):
![code_2018-06-29_14-15-03](https://user-images.githubusercontent.com/20681851/42087448-426b1698-7ba7-11e8-8235-1cf4f36ae344.png)

Error passed into aggregate's cb (and consoled in Chrome > Debugger):
![code_2018-06-29_14-12-38](https://user-images.githubusercontent.com/20681851/42087515-75ce48de-7ba7-11e8-886e-922f8e4fe7dd.png)

Value before "parse":
![code_2018-06-29_14-09-08](https://user-images.githubusercontent.com/20681851/42087537-86cc00f4-7ba7-11e8-9db1-3e7333bd4e1d.png)

Value after "parse":
![code_2018-06-29_14-10-55](https://user-images.githubusercontent.com/20681851/42087556-95ae9a1e-7ba7-11e8-8d51-817daae8f76e.png)

Cause of bug:
![code_2018-06-29_14-14-35](https://user-images.githubusercontent.com/20681851/42087585-a84318da-7ba7-11e8-8577-e51d2f2a4829.png)

**Comment by nadeemramsing** [comment]
A "typeof obj[key] === 'string'" could be added to ObjectId.isValid.

![code_2018-06-29_15-41-19](https://user-images.githubusercontent.com/20681851/42090544-e9ae77a0-7bb2-11e8-872b-62bf0804b3ff.png)

**Comment by adarshasnah** [comment]
solved in release 0.1.12
