### ISSUE TITLE
ENHANCEMENT: controller > aggregate > parse(req.body) > ISOString

### ISSUE THREAD

**Issue by nadeemramsing** [adarshasnah/mongoose-rest-query#2]
### Description:
For equality comparisons to work when using aggregate with **dates**, Date instances must be used instead of "string" (even if it's in the ISOString form).

### Proof:
**Testing using "string"**
![javaw_2018-07-03_10-05-04](https://user-images.githubusercontent.com/20681851/42202762-ab47e3a4-7ead-11e8-9eb0-95b8d8ab4a43.png)

**Testing using Date instances**
![javaw_2018-07-03_10-04-19](https://user-images.githubusercontent.com/20681851/42202785-be49887c-7ead-11e8-8579-730a4b8c0872.png)

### Tried and failed workaround:
**Using Date instances from client app**
![code_2018-07-03_10-03-27](https://user-images.githubusercontent.com/20681851/42202831-e7e99686-7ead-11e8-85bc-17937633ad73.png)

**Automatically gets converted to "string" (most probably by Angular's internal methods)**
![chrome_2018-07-03_10-01-49](https://user-images.githubusercontent.com/20681851/42202882-1e6ae764-7eae-11e8-839b-2c8855ce932f.png)

**Inspected interceptor, but no conversion done here**
![chrome_2018-07-03_10-07-55](https://user-images.githubusercontent.com/20681851/42202907-33a91420-7eae-11e8-80d9-284e0cf26299.png)

### Proposed solution:
**Adding "ISOString to Date" conversion**
![code_2018-07-03_10-33-54](https://user-images.githubusercontent.com/20681851/42202957-594c3f40-7eae-11e8-994c-1504a1ea7a6c.png)

Note: https://github.com/honeinc/is-iso-date used to check if a string is an ISOString,

**Before conversion**
![code_2018-07-03_10-35-47](https://user-images.githubusercontent.com/20681851/42203001-851e405a-7eae-11e8-958d-b35979a2390c.png)

**Comment by adarshasnah** [comment]
enhancement added in version 0.1.13
